name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: pnpm/action-setup@v2.4.0
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
            - name: Install Dependencies
              run: pnpm install
            - name: test
              run: pnpm run test:coverage
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
