name: PNPM Publish

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: pnpm/action-setup@v2.4.0
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
            - name: Install Dependencies
              run: pnpm install
            - run: pnpm build
            - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
            - run: npm publish
